name: Build README
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set safe.directory for Git inside container
        run: git config --global --add safe.directory /github/workspace

      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.1
        with:
          description: |
            This repository is a daily record of what I have learned.
            I document insights from books, lectures, and official documentation in a concise and structured format using Markdown.
            "Small steps every day lead to big results." 🚀
          list_most_recent: 2
          date_format: "2020 Jan 15:04"
